int factorial(int n);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _putchar(char c);
int _strlen_recursion(char *s);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int sqr(int n, int x);
int is_prime_number(int n);
int prime(int n, int x);
int is_palindrome(char *s);
int palindrome(char *s, int first, int last);
int _strlen_recursion(char *s);
int wildcmp(char *s1, char *s2);
